import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-700 md:max-w-2xl">
          <div className="flex border-b border-slate-700 p-4">
            {user.isSignedIn ? (
              <SignOutButton />
            ) : (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            <div>
              {user.isSignedIn
                ? `Hi, ${user.user.firstName} ${user.user.lastName}`
                : null}
            </div>
          </div>
          <div className="flex flex-col">
            {data?.length === 0 && <div>No posts yet</div>}
            {data?.map((post) => (
              <div key={post.id} className="border-b border-slate-700 p-8">
                {post.content}
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
